# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "LaraJournal"

# A description of your site for meta tag, search engine results.
description: "LaraJournal is a simple blog app written on PHP and Laravel"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: "blog"

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://larajournal.github.io"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: "G-3712TB0863"

# Yandex.Metrika counter
yandex_metrika: "99021176"

# Site navigation - each item must have a title and a url.
navigation:
  - text: Blogs Home
    url: /
  - text: About LaraJournal
    url: https://larajournal.github.io
  - text: On GitHub
    url: https://github.com/larajournal/larajournal

# The shortname for your Disqus site to enable comments.
disqus: larajournal

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "Theme by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: false

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
